// Hearthfire Quest Library — 144 Quests Across 8 Domains
// Auto-generated from the Quest Library companion document v1.0

export const QUEST_DATA = [
  // ═══════════════════════════════════════════════════════════════
  // Domain 1: Daily Living & Independence
  // ═══════════════════════════════════════════════════════════════

  // Level 1: Recruit
  {
    key: "dailyLiving-1-1",
    domain: "dailyLiving",
    domainName: "Daily Living & Independence",
    level: 1,
    title: "Space Audit",
    description: "Take photos of your room. Identify 3 \"problem zones\" where stuff accumulates.",
    reflectionPrompt: "Why do things pile up there?",
    difficulty: 1,
  },
  {
    key: "dailyLiving-1-2",
    domain: "dailyLiving",
    domainName: "Daily Living & Independence",
    level: 1,
    title: "Morning Map",
    description: "Write out what you actually do from alarm to leaving. Time each step.",
    reflectionPrompt: "Where does time disappear?",
    difficulty: 1,
  },
  {
    key: "dailyLiving-1-3",
    domain: "dailyLiving",
    domainName: "Daily Living & Independence",
    level: 1,
    title: "Essentials Inventory",
    description: "List everything you need daily. Where does each item \"live\"?",
    reflectionPrompt: "What has no home?",
    difficulty: 1,
  },

  // Level 2: Scout
  {
    key: "dailyLiving-2-1",
    domain: "dailyLiving",
    domainName: "Daily Living & Independence",
    level: 2,
    title: "Zone Defense",
    description: "Pick one problem zone. Create a system. Maintain it for 5 days.",
    reflectionPrompt: "What made it stick (or not)?",
    difficulty: 1,
  },
  {
    key: "dailyLiving-2-2",
    domain: "dailyLiving",
    domainName: "Daily Living & Independence",
    level: 2,
    title: "Morning Speedrun",
    description: "Cut 10 minutes off your morning routine. Document how.",
    reflectionPrompt: "What was actually unnecessary?",
    difficulty: 1,
  },
  {
    key: "dailyLiving-2-3",
    domain: "dailyLiving",
    domainName: "Daily Living & Independence",
    level: 2,
    title: "Laundry Cycle",
    description: "Do your own laundry start to finish without reminders.",
    reflectionPrompt: "What almost went wrong?",
    difficulty: 1,
  },

  // Level 3: Pathfinder
  {
    key: "dailyLiving-3-1",
    domain: "dailyLiving",
    domainName: "Daily Living & Independence",
    level: 3,
    title: "Meal Prep",
    description: "Plan, shop for, and prepare 3 meals this week.",
    reflectionPrompt: "What would you do differently?",
    difficulty: 2,
  },
  {
    key: "dailyLiving-3-2",
    domain: "dailyLiving",
    domainName: "Daily Living & Independence",
    level: 3,
    title: "Guest Ready",
    description: "Get your space \"friend visit ready\" in under 30 minutes.",
    reflectionPrompt: "What's your minimum viable clean?",
    difficulty: 2,
  },
  {
    key: "dailyLiving-3-3",
    domain: "dailyLiving",
    domainName: "Daily Living & Independence",
    level: 3,
    title: "Lost Protocol",
    description: "Lose something (or pretend). Document your search/recovery process.",
    reflectionPrompt: "What system would prevent this?",
    difficulty: 2,
  },

  // Level 4: Ranger
  {
    key: "dailyLiving-4-1",
    domain: "dailyLiving",
    domainName: "Daily Living & Independence",
    level: 4,
    title: "Week Unassisted",
    description: "Handle all daily living tasks for 7 days with zero parental reminders.",
    reflectionPrompt: "Where did you struggle?",
    difficulty: 2,
  },
  {
    key: "dailyLiving-4-2",
    domain: "dailyLiving",
    domainName: "Daily Living & Independence",
    level: 4,
    title: "Budget Meal Challenge",
    description: "Feed yourself for a week on $X. Plan, execute, document.",
    reflectionPrompt: "What surprised you about costs?",
    difficulty: 2,
  },
  {
    key: "dailyLiving-4-3",
    domain: "dailyLiving",
    domainName: "Daily Living & Independence",
    level: 4,
    title: "Deep Clean",
    description: "Full room reset — not just tidy, actually clean.",
    reflectionPrompt: "How often does this need to happen?",
    difficulty: 2,
  },

  // Level 5: Trailblazer
  {
    key: "dailyLiving-5-1",
    domain: "dailyLiving",
    domainName: "Daily Living & Independence",
    level: 5,
    title: "Travel Pack",
    description: "Pack for a 3-day trip. Only what you packed. Debrief what you forgot.",
    reflectionPrompt: "What's your packing checklist now?",
    difficulty: 3,
  },
  {
    key: "dailyLiving-5-2",
    domain: "dailyLiving",
    domainName: "Daily Living & Independence",
    level: 5,
    title: "Shared Space Sim",
    description: "Negotiate and maintain a shared space (bathroom, kitchen) for 2 weeks.",
    reflectionPrompt: "What conflicts came up? How'd you handle them?",
    difficulty: 3,
  },
  {
    key: "dailyLiving-5-3",
    domain: "dailyLiving",
    domainName: "Daily Living & Independence",
    level: 5,
    title: "Maintenance Calendar",
    description: "Create a recurring task calendar (laundry, cleaning, etc.) Follow for 1 month.",
    reflectionPrompt: "What intervals work?",
    difficulty: 3,
  },

  // Level 6: Navigator
  {
    key: "dailyLiving-6-1",
    domain: "dailyLiving",
    domainName: "Daily Living & Independence",
    level: 6,
    title: "Dorm Simulation",
    description: "Live out of one room for a week. All your stuff, limited space.",
    reflectionPrompt: "What would you not bring to college?",
    difficulty: 3,
  },
  {
    key: "dailyLiving-6-2",
    domain: "dailyLiving",
    domainName: "Daily Living & Independence",
    level: 6,
    title: "Independence Week",
    description: "Full self-sufficiency for 7 days. Parents available for emergency only.",
    reflectionPrompt: "What was hardest? What was fine?",
    difficulty: 3,
  },

  // Level 7: Expedition Leader
  {
    key: "dailyLiving-7-1",
    domain: "dailyLiving",
    domainName: "Daily Living & Independence",
    level: 7,
    title: "System Design",
    description: "Design a daily living onboarding guide for an incoming college freshman.",
    reflectionPrompt: "What do people not realize they need to know?",
    difficulty: 3,
  },

  // ═══════════════════════════════════════════════════════════════
  // Domain 2: Physical Health & Self-Care
  // ═══════════════════════════════════════════════════════════════

  // Level 1: Recruit
  {
    key: "health-1-1",
    domain: "health",
    domainName: "Physical Health & Self-Care",
    level: 1,
    title: "Med Mapping",
    description: "Document your medication: what, when, why, what happens if missed.",
    reflectionPrompt: "What do you actually know vs. assume?",
    difficulty: 1,
  },
  {
    key: "health-1-2",
    domain: "health",
    domainName: "Physical Health & Self-Care",
    level: 1,
    title: "Sleep Tracker",
    description: "Log sleep/wake times for 7 days. No judgment, just data.",
    reflectionPrompt: "What patterns do you see?",
    difficulty: 1,
  },
  {
    key: "health-1-3",
    domain: "health",
    domainName: "Physical Health & Self-Care",
    level: 1,
    title: "Body Basics",
    description: "List all health maintenance you're supposed to do (dental, vision, etc.) When was each last done?",
    reflectionPrompt: "What's overdue?",
    difficulty: 1,
  },

  // Level 2: Scout
  {
    key: "health-2-1",
    domain: "health",
    domainName: "Physical Health & Self-Care",
    level: 2,
    title: "Refill Drill",
    description: "Handle your next prescription refill independently. Document steps.",
    reflectionPrompt: "What almost went wrong?",
    difficulty: 1,
  },
  {
    key: "health-2-2",
    domain: "health",
    domainName: "Physical Health & Self-Care",
    level: 2,
    title: "Sleep Experiment",
    description: "Try one change to your sleep routine for 5 days. Report results.",
    reflectionPrompt: "Did it help? Why/why not?",
    difficulty: 1,
  },
  {
    key: "health-2-3",
    domain: "health",
    domainName: "Physical Health & Self-Care",
    level: 2,
    title: "Movement Baseline",
    description: "Track physical activity for a week. Honest assessment.",
    reflectionPrompt: "What's realistic to maintain?",
    difficulty: 1,
  },

  // Level 3: Pathfinder
  {
    key: "health-3-1",
    domain: "health",
    domainName: "Physical Health & Self-Care",
    level: 3,
    title: "Appointment Independence",
    description: "Schedule and attend a health appointment without parental involvement.",
    reflectionPrompt: "What was the process?",
    difficulty: 2,
  },
  {
    key: "health-3-2",
    domain: "health",
    domainName: "Physical Health & Self-Care",
    level: 3,
    title: "Pharmacy Relationship",
    description: "Introduce yourself at the pharmacy. Know how to reach them, how refills work.",
    reflectionPrompt: "What did you learn?",
    difficulty: 2,
  },
  {
    key: "health-3-3",
    domain: "health",
    domainName: "Physical Health & Self-Care",
    level: 3,
    title: "Sick Day Protocol",
    description: "Get sick (or simulate). Handle it: meds, rest, communication.",
    reflectionPrompt: "What do you need when sick?",
    difficulty: 2,
  },

  // Level 4: Ranger
  {
    key: "health-4-1",
    domain: "health",
    domainName: "Physical Health & Self-Care",
    level: 4,
    title: "Health Ownership Month",
    description: "Manage all health tasks for 30 days. Meds, appointments, refills, your job.",
    reflectionPrompt: "What systems did you build?",
    difficulty: 2,
  },
  {
    key: "health-4-2",
    domain: "health",
    domainName: "Physical Health & Self-Care",
    level: 4,
    title: "Insurance Basics",
    description: "Learn: who's your insurance, what's your ID number, how do you use it?",
    reflectionPrompt: "What's still confusing?",
    difficulty: 2,
  },
  {
    key: "health-4-3",
    domain: "health",
    domainName: "Physical Health & Self-Care",
    level: 4,
    title: "Campus Health Research",
    description: "Research health services at your target colleges. What's available?",
    reflectionPrompt: "What would you do if you got sick there?",
    difficulty: 2,
  },

  // Level 5: Trailblazer
  {
    key: "health-5-1",
    domain: "health",
    domainName: "Physical Health & Self-Care",
    level: 5,
    title: "Health Record Access",
    description: "Get access to your patient portal. Know how to see records, message doctors.",
    reflectionPrompt: "What information is there?",
    difficulty: 3,
  },
  {
    key: "health-5-2",
    domain: "health",
    domainName: "Physical Health & Self-Care",
    level: 5,
    title: "Emergency Prep",
    description: "Know your allergies, medications, emergency contacts, insurance info from memory.",
    reflectionPrompt: "What did you have to look up?",
    difficulty: 3,
  },
  {
    key: "health-5-3",
    domain: "health",
    domainName: "Physical Health & Self-Care",
    level: 5,
    title: "Prescription Transfer",
    description: "Research how to transfer a prescription to a new pharmacy (for college).",
    reflectionPrompt: "What's the process?",
    difficulty: 3,
  },

  // Level 6: Navigator
  {
    key: "health-6-1",
    domain: "health",
    domainName: "Physical Health & Self-Care",
    level: 6,
    title: "Health Independence Audit",
    description: "Full assessment: what health tasks can you handle alone? What still needs support?",
    reflectionPrompt: "What's the gap?",
    difficulty: 3,
  },
  {
    key: "health-6-2",
    domain: "health",
    domainName: "Physical Health & Self-Care",
    level: 6,
    title: "Medication Travel",
    description: "Manage meds during a trip away from home (weekend or longer).",
    reflectionPrompt: "What's your travel system?",
    difficulty: 3,
  },

  // Level 7: Expedition Leader
  {
    key: "health-7-1",
    domain: "health",
    domainName: "Physical Health & Self-Care",
    level: 7,
    title: "Health Transition Plan",
    description: "Create your complete health management plan for college: providers, pharmacy, records, emergency protocol.",
    reflectionPrompt: "What would you tell another student?",
    difficulty: 3,
  },

  // ═══════════════════════════════════════════════════════════════
  // Domain 3: Time Management & Follow-Through
  // ═══════════════════════════════════════════════════════════════

  // Level 1: Recruit
  {
    key: "timeManagement-1-1",
    domain: "timeManagement",
    domainName: "Time Management & Follow-Through",
    level: 1,
    title: "Time Detective",
    description: "Estimate how long 5 regular tasks take. Then time them. Document the gaps.",
    reflectionPrompt: "Where were you most wrong?",
    difficulty: 1,
  },
  {
    key: "timeManagement-1-2",
    domain: "timeManagement",
    domainName: "Time Management & Follow-Through",
    level: 1,
    title: "Calendar Audit",
    description: "Look at your current calendar/planner use. What's there? What's missing?",
    reflectionPrompt: "What do you actually use?",
    difficulty: 1,
  },
  {
    key: "timeManagement-1-3",
    domain: "timeManagement",
    domainName: "Time Management & Follow-Through",
    level: 1,
    title: "Deadline Inventory",
    description: "List everything due in the next 2 weeks. All sources.",
    reflectionPrompt: "What almost got missed?",
    difficulty: 1,
  },

  // Level 2: Scout
  {
    key: "timeManagement-2-1",
    domain: "timeManagement",
    domainName: "Time Management & Follow-Through",
    level: 2,
    title: "Buffer Builder",
    description: "Identify 3 situations where you're regularly late. Build in buffers. Test for 1 week.",
    reflectionPrompt: "Did the buffers help?",
    difficulty: 1,
  },
  {
    key: "timeManagement-2-2",
    domain: "timeManagement",
    domainName: "Time Management & Follow-Through",
    level: 2,
    title: "Single Project Plan",
    description: "Take one upcoming task. Break it into steps. Assign times. Execute.",
    reflectionPrompt: "How did plan vs. reality compare?",
    difficulty: 1,
  },
  {
    key: "timeManagement-2-3",
    domain: "timeManagement",
    domainName: "Time Management & Follow-Through",
    level: 2,
    title: "Reminder System",
    description: "Set up a reminder system for recurring tasks. Use for 2 weeks.",
    reflectionPrompt: "What worked? What got ignored?",
    difficulty: 1,
  },

  // Level 3: Pathfinder
  {
    key: "timeManagement-3-1",
    domain: "timeManagement",
    domainName: "Time Management & Follow-Through",
    level: 3,
    title: "Multi-Deadline Week",
    description: "You have 3+ things due this week. Make a plan, execute, document what happened.",
    reflectionPrompt: "Where did the plan break?",
    difficulty: 2,
  },
  {
    key: "timeManagement-3-2",
    domain: "timeManagement",
    domainName: "Time Management & Follow-Through",
    level: 3,
    title: "Transition Tracking",
    description: "Log every transition between activities for 3 days. How long do transitions take?",
    reflectionPrompt: "What's eating time?",
    difficulty: 2,
  },
  {
    key: "timeManagement-3-3",
    domain: "timeManagement",
    domainName: "Time Management & Follow-Through",
    level: 3,
    title: "On-Time Challenge",
    description: "Be on time (or early) to everything for 5 days.",
    reflectionPrompt: "What did it take?",
    difficulty: 2,
  },

  // Level 4: Ranger
  {
    key: "timeManagement-4-1",
    domain: "timeManagement",
    domainName: "Time Management & Follow-Through",
    level: 4,
    title: "Long-Term Project",
    description: "Manage a project with a deadline 2+ weeks out. Plan backwards, execute in stages.",
    reflectionPrompt: "When did you actually do the work?",
    difficulty: 2,
  },
  {
    key: "timeManagement-4-2",
    domain: "timeManagement",
    domainName: "Time Management & Follow-Through",
    level: 4,
    title: "Recovery Protocol",
    description: "Something fell through. Document: what happened, what you did to recover, what you'd do differently.",
    reflectionPrompt: "How did recovery go?",
    difficulty: 2,
  },
  {
    key: "timeManagement-4-3",
    domain: "timeManagement",
    domainName: "Time Management & Follow-Through",
    level: 4,
    title: "Time Blocking Week",
    description: "Schedule your week in advance with time blocks. Follow the plan. Report accuracy.",
    reflectionPrompt: "What was realistic? What wasn't?",
    difficulty: 2,
  },

  // Level 5: Trailblazer
  {
    key: "timeManagement-5-1",
    domain: "timeManagement",
    domainName: "Time Management & Follow-Through",
    level: 5,
    title: "Competing Priorities",
    description: "A week with multiple important things. Document your prioritization decisions.",
    reflectionPrompt: "How did you decide what mattered most?",
    difficulty: 3,
  },
  {
    key: "timeManagement-5-2",
    domain: "timeManagement",
    domainName: "Time Management & Follow-Through",
    level: 5,
    title: "Crunch Simulation",
    description: "You have a paper/project due tomorrow and you're behind. Execute. Debrief.",
    reflectionPrompt: "What's your crunch protocol?",
    difficulty: 3,
  },
  {
    key: "timeManagement-5-3",
    domain: "timeManagement",
    domainName: "Time Management & Follow-Through",
    level: 5,
    title: "No Reminders Week",
    description: "Turn off external reminders. Manage your schedule independently.",
    reflectionPrompt: "What did you miss?",
    difficulty: 3,
  },

  // Level 6: Navigator
  {
    key: "timeManagement-6-1",
    domain: "timeManagement",
    domainName: "Time Management & Follow-Through",
    level: 6,
    title: "Semester Simulation",
    description: "Map out a hypothetical college semester: classes, activities, deadlines. How would you manage it?",
    reflectionPrompt: "What's your system?",
    difficulty: 3,
  },
  {
    key: "timeManagement-6-2",
    domain: "timeManagement",
    domainName: "Time Management & Follow-Through",
    level: 6,
    title: "Failure Recovery Challenge",
    description: "Intentionally miss a self-imposed deadline. Practice the recovery process.",
    reflectionPrompt: "What's your recovery checklist?",
    difficulty: 3,
  },

  // Level 7: Expedition Leader
  {
    key: "timeManagement-7-1",
    domain: "timeManagement",
    domainName: "Time Management & Follow-Through",
    level: 7,
    title: "Time System Documentation",
    description: "Write up your complete time management system for another student.",
    reflectionPrompt: "What's essential vs. personal preference?",
    difficulty: 3,
  },

  // ═══════════════════════════════════════════════════════════════
  // Domain 4: Social Skills & Relationships
  // ═══════════════════════════════════════════════════════════════

  // Level 1: Recruit
  {
    key: "social-1-1",
    domain: "social",
    domainName: "Social Skills & Relationships",
    level: 1,
    title: "Social Map",
    description: "List your current relationships: friends, acquaintances, mentors. Who do you reach out to vs. wait for?",
    reflectionPrompt: "Where are you proactive vs. passive?",
    difficulty: 1,
  },
  {
    key: "social-1-2",
    domain: "social",
    domainName: "Social Skills & Relationships",
    level: 1,
    title: "Initiative Inventory",
    description: "How many social plans have you initiated in the past month?",
    reflectionPrompt: "What stops you from initiating?",
    difficulty: 1,
  },
  {
    key: "social-1-3",
    domain: "social",
    domainName: "Social Skills & Relationships",
    level: 1,
    title: "Conflict Recall",
    description: "Think of a recent friction with someone. What happened? What did you do?",
    reflectionPrompt: "What would you do differently?",
    difficulty: 1,
  },

  // Level 2: Scout
  {
    key: "social-2-1",
    domain: "social",
    domainName: "Social Skills & Relationships",
    level: 2,
    title: "Initiate",
    description: "Make a plan with a friend (not family). You initiate, you coordinate.",
    reflectionPrompt: "How did it go?",
    difficulty: 1,
  },
  {
    key: "social-2-2",
    domain: "social",
    domainName: "Social Skills & Relationships",
    level: 2,
    title: "Small Talk Practice",
    description: "Have a conversation with someone you don't know well (cashier, classmate).",
    reflectionPrompt: "What did you notice?",
    difficulty: 1,
  },
  {
    key: "social-2-3",
    domain: "social",
    domainName: "Social Skills & Relationships",
    level: 2,
    title: "Check-In",
    description: "Reach out to someone you haven't talked to in a while. Just to say hi.",
    reflectionPrompt: "What response did you get?",
    difficulty: 1,
  },

  // Level 3: Pathfinder
  {
    key: "social-3-1",
    domain: "social",
    domainName: "Social Skills & Relationships",
    level: 3,
    title: "Group Coordination",
    description: "Organize an activity involving 3+ people. Handle the logistics.",
    reflectionPrompt: "What was harder than expected?",
    difficulty: 2,
  },
  {
    key: "social-3-2",
    domain: "social",
    domainName: "Social Skills & Relationships",
    level: 3,
    title: "Boundary Practice",
    description: "A situation where you need to say no or set a limit. Plan it, do it, report.",
    reflectionPrompt: "How did it feel? How'd they react?",
    difficulty: 2,
  },
  {
    key: "social-3-3",
    domain: "social",
    domainName: "Social Skills & Relationships",
    level: 3,
    title: "Roommate Simulation",
    description: "Share a space with someone for a weekend. Navigate preferences and conflicts.",
    reflectionPrompt: "What came up? How'd you handle it?",
    difficulty: 2,
  },

  // Level 4: Ranger
  {
    key: "social-4-1",
    domain: "social",
    domainName: "Social Skills & Relationships",
    level: 4,
    title: "Difficult Conversation",
    description: "A conversation you've been avoiding. Prepare for it, have it, debrief.",
    reflectionPrompt: "What did you prepare? What helped?",
    difficulty: 2,
  },
  {
    key: "social-4-2",
    domain: "social",
    domainName: "Social Skills & Relationships",
    level: 4,
    title: "Social Recovery",
    description: "Something went wrong socially (real or recent). Make it right.",
    reflectionPrompt: "What did repair look like?",
    difficulty: 2,
  },
  {
    key: "social-4-3",
    domain: "social",
    domainName: "Social Skills & Relationships",
    level: 4,
    title: "New Person",
    description: "Meet someone new. Not online — in person.",
    reflectionPrompt: "How did you initiate?",
    difficulty: 2,
  },

  // Level 5: Trailblazer
  {
    key: "social-5-1",
    domain: "social",
    domainName: "Social Skills & Relationships",
    level: 5,
    title: "Event Attendance",
    description: "Attend a social event where you don't know most people. Solo.",
    reflectionPrompt: "What was your strategy?",
    difficulty: 3,
  },
  {
    key: "social-5-2",
    domain: "social",
    domainName: "Social Skills & Relationships",
    level: 5,
    title: "Support Request",
    description: "Ask someone for help with something real.",
    reflectionPrompt: "What made it hard? What made it easier?",
    difficulty: 3,
  },
  {
    key: "social-5-3",
    domain: "social",
    domainName: "Social Skills & Relationships",
    level: 5,
    title: "Mentor Check-In",
    description: "Reach out to a teacher, coach, or mentor. Update them on your life.",
    reflectionPrompt: "What was that conversation like?",
    difficulty: 3,
  },

  // Level 6: Navigator
  {
    key: "social-6-1",
    domain: "social",
    domainName: "Social Skills & Relationships",
    level: 6,
    title: "Relationship Maintenance System",
    description: "Create a system for staying in touch with important people. Use for 1 month.",
    reflectionPrompt: "What intervals make sense?",
    difficulty: 3,
  },
  {
    key: "social-6-2",
    domain: "social",
    domainName: "Social Skills & Relationships",
    level: 6,
    title: "Conflict Navigation",
    description: "Handle a real disagreement without escalation or withdrawal.",
    reflectionPrompt: "What was your approach?",
    difficulty: 3,
  },

  // Level 7: Expedition Leader
  {
    key: "social-7-1",
    domain: "social",
    domainName: "Social Skills & Relationships",
    level: 7,
    title: "Social Survival Guide",
    description: "Write your advice for a new college student on making friends and handling roommates.",
    reflectionPrompt: "What do you wish you'd known earlier?",
    difficulty: 3,
  },

  // ═══════════════════════════════════════════════════════════════
  // Domain 5: Mental Health & Emotional Regulation
  // ═══════════════════════════════════════════════════════════════

  // Level 1: Recruit
  {
    key: "mentalHealth-1-1",
    domain: "mentalHealth",
    domainName: "Mental Health & Emotional Regulation",
    level: 1,
    title: "Stress Signals",
    description: "List your personal signs that stress is building (physical, behavioral, emotional).",
    reflectionPrompt: "How early can you notice them?",
    difficulty: 1,
  },
  {
    key: "mentalHealth-1-2",
    domain: "mentalHealth",
    domainName: "Mental Health & Emotional Regulation",
    level: 1,
    title: "Coping Inventory",
    description: "What do you currently do when overwhelmed? List everything (helpful and unhelpful).",
    reflectionPrompt: "What actually helps vs. just feels good?",
    difficulty: 1,
  },
  {
    key: "mentalHealth-1-3",
    domain: "mentalHealth",
    domainName: "Mental Health & Emotional Regulation",
    level: 1,
    title: "Support Map",
    description: "Who could you talk to if you were struggling? List people and what each is good for.",
    reflectionPrompt: "Who's missing?",
    difficulty: 1,
  },

  // Level 2: Scout
  {
    key: "mentalHealth-2-1",
    domain: "mentalHealth",
    domainName: "Mental Health & Emotional Regulation",
    level: 2,
    title: "Coping Test",
    description: "Try one coping strategy you don't usually use. Report results.",
    reflectionPrompt: "Did it work? Why/why not?",
    difficulty: 1,
  },
  {
    key: "mentalHealth-2-2",
    domain: "mentalHealth",
    domainName: "Mental Health & Emotional Regulation",
    level: 2,
    title: "Mood Tracking",
    description: "Track your mood for a week. Simple scale, brief notes on context.",
    reflectionPrompt: "What patterns do you see?",
    difficulty: 1,
  },
  {
    key: "mentalHealth-2-3",
    domain: "mentalHealth",
    domainName: "Mental Health & Emotional Regulation",
    level: 2,
    title: "Early Intervention",
    description: "Catch stress early and intervene before it escalates. Document.",
    reflectionPrompt: "What was your early warning?",
    difficulty: 1,
  },

  // Level 3: Pathfinder
  {
    key: "mentalHealth-3-1",
    domain: "mentalHealth",
    domainName: "Mental Health & Emotional Regulation",
    level: 3,
    title: "Bad Day Protocol",
    description: "A bad day happens (or will). Handle it. What's your protocol?",
    reflectionPrompt: "What worked? What didn't?",
    difficulty: 2,
  },
  {
    key: "mentalHealth-3-2",
    domain: "mentalHealth",
    domainName: "Mental Health & Emotional Regulation",
    level: 3,
    title: "Frustration Tolerance",
    description: "A frustrating situation. Notice the feeling. Don't react impulsively. Debrief.",
    reflectionPrompt: "What did you do with the frustration?",
    difficulty: 2,
  },
  {
    key: "mentalHealth-3-3",
    domain: "mentalHealth",
    domainName: "Mental Health & Emotional Regulation",
    level: 3,
    title: "Help Research",
    description: "Research mental health resources at your target colleges. What's available?",
    reflectionPrompt: "What would you access if needed?",
    difficulty: 2,
  },

  // Level 4: Ranger
  {
    key: "mentalHealth-4-1",
    domain: "mentalHealth",
    domainName: "Mental Health & Emotional Regulation",
    level: 4,
    title: "Spiral Prevention",
    description: "Catch yourself heading toward a shutdown/spiral. Intervene. Document.",
    reflectionPrompt: "What stopped the spiral?",
    difficulty: 2,
  },
  {
    key: "mentalHealth-4-2",
    domain: "mentalHealth",
    domainName: "Mental Health & Emotional Regulation",
    level: 4,
    title: "Rejection Practice",
    description: "Experience a small rejection (ask for something and get told no). Process it.",
    reflectionPrompt: "What did your brain do? What did you do?",
    difficulty: 2,
  },
  {
    key: "mentalHealth-4-3",
    domain: "mentalHealth",
    domainName: "Mental Health & Emotional Regulation",
    level: 4,
    title: "Accountability Share",
    description: "Tell someone you trust about something you're struggling with.",
    reflectionPrompt: "What did sharing feel like?",
    difficulty: 2,
  },

  // Level 5: Trailblazer
  {
    key: "mentalHealth-5-1",
    domain: "mentalHealth",
    domainName: "Mental Health & Emotional Regulation",
    level: 5,
    title: "Mental Health Check-Up",
    description: "If available, have a session with a counselor. Or do a thorough self-assessment.",
    reflectionPrompt: "What did you learn about your current state?",
    difficulty: 3,
  },
  {
    key: "mentalHealth-5-2",
    domain: "mentalHealth",
    domainName: "Mental Health & Emotional Regulation",
    level: 5,
    title: "Crisis Plan",
    description: "Write your personal crisis plan: warning signs, coping steps, who to call.",
    reflectionPrompt: "What would you do in an emergency?",
    difficulty: 3,
  },
  {
    key: "mentalHealth-5-3",
    domain: "mentalHealth",
    domainName: "Mental Health & Emotional Regulation",
    level: 5,
    title: "Emotional Regulation Challenge",
    description: "A high-emotion week. Track how you handled the highs and lows.",
    reflectionPrompt: "What's your range like?",
    difficulty: 3,
  },

  // Level 6: Navigator
  {
    key: "mentalHealth-6-1",
    domain: "mentalHealth",
    domainName: "Mental Health & Emotional Regulation",
    level: 6,
    title: "Independence Stress Test",
    description: "Handle a stressful situation without immediate parental support.",
    reflectionPrompt: "What resources did you use instead?",
    difficulty: 3,
  },
  {
    key: "mentalHealth-6-2",
    domain: "mentalHealth",
    domainName: "Mental Health & Emotional Regulation",
    level: 6,
    title: "Therapy/Counseling Navigation",
    description: "If you needed a therapist at college, how would you get one? Research the process.",
    reflectionPrompt: "What's the pathway?",
    difficulty: 3,
  },

  // Level 7: Expedition Leader
  {
    key: "mentalHealth-7-1",
    domain: "mentalHealth",
    domainName: "Mental Health & Emotional Regulation",
    level: 7,
    title: "Mental Health Toolkit",
    description: "Document your complete mental health toolkit: warning signs, coping strategies, supports, crisis plan.",
    reflectionPrompt: "What would you tell another student?",
    difficulty: 3,
  },

  // ═══════════════════════════════════════════════════════════════
  // Domain 6: Safety, Judgment & Impulse Control
  // ═══════════════════════════════════════════════════════════════

  // Level 1: Recruit
  {
    key: "safety-1-1",
    domain: "safety",
    domainName: "Safety, Judgment & Impulse Control",
    level: 1,
    title: "Impulse Awareness",
    description: "Track 3 moments this week where you wanted to do something impulsive. What did you do?",
    reflectionPrompt: "What triggers impulse?",
    difficulty: 1,
  },
  {
    key: "safety-1-2",
    domain: "safety",
    domainName: "Safety, Judgment & Impulse Control",
    level: 1,
    title: "Decision Replay",
    description: "Think of a recent decision that didn't go well. Walk through your thinking at the time.",
    reflectionPrompt: "Where did the logic break down?",
    difficulty: 1,
  },
  {
    key: "safety-1-3",
    domain: "safety",
    domainName: "Safety, Judgment & Impulse Control",
    level: 1,
    title: "Risk Inventory",
    description: "What risky things do you currently do? Be honest.",
    reflectionPrompt: "What are the actual stakes?",
    difficulty: 1,
  },

  // Level 2: Scout
  {
    key: "safety-2-1",
    domain: "safety",
    domainName: "Safety, Judgment & Impulse Control",
    level: 2,
    title: "Pause Practice",
    description: "In an impulsive moment, pause for 60 seconds before acting. Document 3 instances.",
    reflectionPrompt: "What happened during the pause?",
    difficulty: 1,
  },
  {
    key: "safety-2-2",
    domain: "safety",
    domainName: "Safety, Judgment & Impulse Control",
    level: 2,
    title: "Scenario Walkthrough",
    description: "Hypothetical: You're at a party and someone offers you something. Talk through your decision tree.",
    reflectionPrompt: "What factors matter?",
    difficulty: 1,
  },
  {
    key: "safety-2-3",
    domain: "safety",
    domainName: "Safety, Judgment & Impulse Control",
    level: 2,
    title: "Consequence Mapping",
    description: "Pick a risky behavior. Map out all possible consequences (not just worst case).",
    reflectionPrompt: "What's the actual probability spread?",
    difficulty: 1,
  },

  // Level 3: Pathfinder
  {
    key: "safety-3-1",
    domain: "safety",
    domainName: "Safety, Judgment & Impulse Control",
    level: 3,
    title: "Peer Pressure Debrief",
    description: "A situation where you felt pressure to do something. What did you do?",
    reflectionPrompt: "What would you do differently?",
    difficulty: 2,
  },
  {
    key: "safety-3-2",
    domain: "safety",
    domainName: "Safety, Judgment & Impulse Control",
    level: 3,
    title: "Safety Planning",
    description: "You're going to an event/situation. What's your safety plan? Make one, execute, debrief.",
    reflectionPrompt: "What did you plan for? What came up?",
    difficulty: 2,
  },
  {
    key: "safety-3-3",
    domain: "safety",
    domainName: "Safety, Judgment & Impulse Control",
    level: 3,
    title: "Boundary Enforcement",
    description: "Someone pushed a boundary. How did you respond?",
    reflectionPrompt: "What made it hard/easy?",
    difficulty: 2,
  },

  // Level 4: Ranger
  {
    key: "safety-4-1",
    domain: "safety",
    domainName: "Safety, Judgment & Impulse Control",
    level: 4,
    title: "High-Stakes Decision",
    description: "A real decision with meaningful consequences. Document your process.",
    reflectionPrompt: "How did you decide?",
    difficulty: 2,
  },
  {
    key: "safety-4-2",
    domain: "safety",
    domainName: "Safety, Judgment & Impulse Control",
    level: 4,
    title: "Consent Conversation",
    description: "Have an explicit conversation about consent/boundaries in some context.",
    reflectionPrompt: "What was that like?",
    difficulty: 2,
  },
  {
    key: "safety-4-3",
    domain: "safety",
    domainName: "Safety, Judgment & Impulse Control",
    level: 4,
    title: "Impulse Victory",
    description: "A moment where you successfully overrode a bad impulse. Document.",
    reflectionPrompt: "What helped you stop?",
    difficulty: 2,
  },

  // Level 5: Trailblazer
  {
    key: "safety-5-1",
    domain: "safety",
    domainName: "Safety, Judgment & Impulse Control",
    level: 5,
    title: "Novel Situation",
    description: "Enter a situation you haven't been in before. Navigate it. Debrief judgment calls.",
    reflectionPrompt: "What did you have to figure out on the fly?",
    difficulty: 3,
  },
  {
    key: "safety-5-2",
    domain: "safety",
    domainName: "Safety, Judgment & Impulse Control",
    level: 5,
    title: "Risk Assessment",
    description: "You want to do something with some risk. Do a real risk assessment. Decide.",
    reflectionPrompt: "How did you weigh costs/benefits?",
    difficulty: 3,
  },
  {
    key: "safety-5-3",
    domain: "safety",
    domainName: "Safety, Judgment & Impulse Control",
    level: 5,
    title: "Emergency Simulation",
    description: "Something goes wrong (flat tire, lost, minor injury). Handle it.",
    reflectionPrompt: "What was your process?",
    difficulty: 3,
  },

  // Level 6: Navigator
  {
    key: "safety-6-1",
    domain: "safety",
    domainName: "Safety, Judgment & Impulse Control",
    level: 6,
    title: "Independence Night",
    description: "A night out with friends, no parental check-in required. Debrief honestly.",
    reflectionPrompt: "What decisions did you make?",
    difficulty: 3,
  },
  {
    key: "safety-6-2",
    domain: "safety",
    domainName: "Safety, Judgment & Impulse Control",
    level: 6,
    title: "Judgment Under Pressure",
    description: "Document a situation where you had to make a quick call.",
    reflectionPrompt: "What did you weigh? What did you miss?",
    difficulty: 3,
  },

  // Level 7: Expedition Leader
  {
    key: "safety-7-1",
    domain: "safety",
    domainName: "Safety, Judgment & Impulse Control",
    level: 7,
    title: "Safety & Judgment Guide",
    description: "Write your advice on parties, substances, safety, consent for an incoming freshman.",
    reflectionPrompt: "What do they need to know?",
    difficulty: 3,
  },

  // ═══════════════════════════════════════════════════════════════
  // Domain 7: ADHD Self-Management & Self-Advocacy
  // ═══════════════════════════════════════════════════════════════

  // Level 1: Recruit
  {
    key: "adhd-1-1",
    domain: "adhd",
    domainName: "ADHD Self-Management & Self-Advocacy",
    level: 1,
    title: "ADHD Self-Portrait",
    description: "How does ADHD specifically affect YOU? Not the textbook — your experience.",
    reflectionPrompt: "What do people not understand?",
    difficulty: 1,
  },
  {
    key: "adhd-1-2",
    domain: "adhd",
    domainName: "ADHD Self-Management & Self-Advocacy",
    level: 1,
    title: "Tool Audit",
    description: "What external supports do you currently use (apps, reminders, systems)? What's missing?",
    reflectionPrompt: "What tools are you resisting?",
    difficulty: 1,
  },
  {
    key: "adhd-1-3",
    domain: "adhd",
    domainName: "ADHD Self-Management & Self-Advocacy",
    level: 1,
    title: "Shame Inventory",
    description: "What ADHD-related things are you embarrassed about?",
    reflectionPrompt: "Where does the shame come from?",
    difficulty: 1,
  },

  // Level 2: Scout
  {
    key: "adhd-2-1",
    domain: "adhd",
    domainName: "ADHD Self-Management & Self-Advocacy",
    level: 2,
    title: "Tool Experiment",
    description: "Try one new external support for a week. Report.",
    reflectionPrompt: "Did it help? What got in the way?",
    difficulty: 1,
  },
  {
    key: "adhd-2-2",
    domain: "adhd",
    domainName: "ADHD Self-Management & Self-Advocacy",
    level: 2,
    title: "Explain Your Brain",
    description: "Explain how ADHD affects you to someone who doesn't have it.",
    reflectionPrompt: "What was hard to explain?",
    difficulty: 1,
  },
  {
    key: "adhd-2-3",
    domain: "adhd",
    domainName: "ADHD Self-Management & Self-Advocacy",
    level: 2,
    title: "Accommodation Research",
    description: "What accommodations exist for ADHD students in college?",
    reflectionPrompt: "What might you need?",
    difficulty: 1,
  },

  // Level 3: Pathfinder
  {
    key: "adhd-3-1",
    domain: "adhd",
    domainName: "ADHD Self-Management & Self-Advocacy",
    level: 3,
    title: "Self-Advocacy Practice",
    description: "Ask for something you need (extra time, a reminder, a modification) from someone other than parents.",
    reflectionPrompt: "How did you ask? What happened?",
    difficulty: 2,
  },
  {
    key: "adhd-3-2",
    domain: "adhd",
    domainName: "ADHD Self-Management & Self-Advocacy",
    level: 3,
    title: "Disability Services Research",
    description: "Research disability services at your target colleges. What's the process?",
    reflectionPrompt: "What would you need to do to register?",
    difficulty: 2,
  },
  {
    key: "adhd-3-3",
    domain: "adhd",
    domainName: "ADHD Self-Management & Self-Advocacy",
    level: 3,
    title: "Shame Challenge",
    description: "Do something ADHD-supportive in front of others (use a fidget, take a note, ask to repeat).",
    reflectionPrompt: "What happened?",
    difficulty: 2,
  },

  // Level 4: Ranger
  {
    key: "adhd-4-1",
    domain: "adhd",
    domainName: "ADHD Self-Management & Self-Advocacy",
    level: 4,
    title: "System Failure & Rebuild",
    description: "A system you rely on failed. Diagnose why. Build a new one.",
    reflectionPrompt: "What did the failure teach you?",
    difficulty: 2,
  },
  {
    key: "adhd-4-2",
    domain: "adhd",
    domainName: "ADHD Self-Management & Self-Advocacy",
    level: 4,
    title: "Accommodation Request",
    description: "Actually request an accommodation from a teacher/employer.",
    reflectionPrompt: "What was the process?",
    difficulty: 2,
  },
  {
    key: "adhd-4-3",
    domain: "adhd",
    domainName: "ADHD Self-Management & Self-Advocacy",
    level: 4,
    title: "ADHD Wins",
    description: "Document 3 things this month that went well BECAUSE of how your brain works.",
    reflectionPrompt: "What are your ADHD strengths?",
    difficulty: 2,
  },

  // Level 5: Trailblazer
  {
    key: "adhd-5-1",
    domain: "adhd",
    domainName: "ADHD Self-Management & Self-Advocacy",
    level: 5,
    title: "New Context Adaptation",
    description: "Enter a new environment. Figure out what supports you need there. Implement them.",
    reflectionPrompt: "How did you adapt your systems?",
    difficulty: 3,
  },
  {
    key: "adhd-5-2",
    domain: "adhd",
    domainName: "ADHD Self-Management & Self-Advocacy",
    level: 5,
    title: "Setback Recovery",
    description: "A significant setback (missed deadline, forgot something important). Recover without spiraling.",
    reflectionPrompt: "What did recovery look like?",
    difficulty: 3,
  },
  {
    key: "adhd-5-3",
    domain: "adhd",
    domainName: "ADHD Self-Management & Self-Advocacy",
    level: 5,
    title: "Disability Services Contact",
    description: "Reach out to disability services at a target school. Ask questions.",
    reflectionPrompt: "What did you learn?",
    difficulty: 3,
  },

  // Level 6: Navigator
  {
    key: "adhd-6-1",
    domain: "adhd",
    domainName: "ADHD Self-Management & Self-Advocacy",
    level: 6,
    title: "Transition Plan",
    description: "Create your ADHD management plan for college: tools, accommodations, supports, backup plans.",
    reflectionPrompt: "What's the system?",
    difficulty: 3,
  },
  {
    key: "adhd-6-2",
    domain: "adhd",
    domainName: "ADHD Self-Management & Self-Advocacy",
    level: 6,
    title: "Advocacy Independence",
    description: "Handle an ADHD-related need without parental involvement.",
    reflectionPrompt: "What did you do?",
    difficulty: 3,
  },

  // Level 7: Expedition Leader
  {
    key: "adhd-7-1",
    domain: "adhd",
    domainName: "ADHD Self-Management & Self-Advocacy",
    level: 7,
    title: "ADHD Survival Guide",
    description: "Write your guide for an ADHD student starting college.",
    reflectionPrompt: "What do you wish someone had told you?",
    difficulty: 3,
  },

  // ═══════════════════════════════════════════════════════════════
  // Domain 8: Academic Independence
  // ═══════════════════════════════════════════════════════════════

  // Level 1: Recruit
  {
    key: "academic-1-1",
    domain: "academic",
    domainName: "Academic Independence",
    level: 1,
    title: "Deadline Archaeology",
    description: "Look back at last semester. Where did you struggle with deadlines? Why?",
    reflectionPrompt: "What patterns do you see?",
    difficulty: 1,
  },
  {
    key: "academic-1-2",
    domain: "academic",
    domainName: "Academic Independence",
    level: 1,
    title: "Help Resource Map",
    description: "What academic help exists (tutoring, office hours, study groups)? Have you used them?",
    reflectionPrompt: "What stops you?",
    difficulty: 1,
  },
  {
    key: "academic-1-3",
    domain: "academic",
    domainName: "Academic Independence",
    level: 1,
    title: "Study Audit",
    description: "How do you actually study? Be honest.",
    reflectionPrompt: "What works? What's just ritual?",
    difficulty: 1,
  },

  // Level 2: Scout
  {
    key: "academic-2-1",
    domain: "academic",
    domainName: "Academic Independence",
    level: 2,
    title: "Office Hours Quest",
    description: "Attend office hours for one class. Ask a question.",
    reflectionPrompt: "What was that like?",
    difficulty: 1,
  },
  {
    key: "academic-2-2",
    domain: "academic",
    domainName: "Academic Independence",
    level: 2,
    title: "Assignment Breakdown",
    description: "Take an upcoming assignment. Break it into steps with time estimates.",
    reflectionPrompt: "How accurate were you?",
    difficulty: 1,
  },
  {
    key: "academic-2-3",
    domain: "academic",
    domainName: "Academic Independence",
    level: 2,
    title: "Study Experiment",
    description: "Try one new study method. Report results.",
    reflectionPrompt: "Did it work for your brain?",
    difficulty: 1,
  },

  // Level 3: Pathfinder
  {
    key: "academic-3-1",
    domain: "academic",
    domainName: "Academic Independence",
    level: 3,
    title: "Help Seeking",
    description: "You're stuck on something. Get help (not from parents). Document the process.",
    reflectionPrompt: "Where did you go? What worked?",
    difficulty: 2,
  },
  {
    key: "academic-3-2",
    domain: "academic",
    domainName: "Academic Independence",
    level: 3,
    title: "Grade Recovery",
    description: "A grade isn't where you want it. Make a plan. Execute. Report.",
    reflectionPrompt: "What did recovery require?",
    difficulty: 2,
  },
  {
    key: "academic-3-3",
    domain: "academic",
    domainName: "Academic Independence",
    level: 3,
    title: "Long Assignment",
    description: "Manage a paper/project with a 2+ week runway. Document your process.",
    reflectionPrompt: "When did you actually work on it?",
    difficulty: 2,
  },

  // Level 4: Ranger
  {
    key: "academic-4-1",
    domain: "academic",
    domainName: "Academic Independence",
    level: 4,
    title: "Multi-Class Management",
    description: "Document how you're managing workload across all classes for 2 weeks.",
    reflectionPrompt: "Where are the conflicts?",
    difficulty: 2,
  },
  {
    key: "academic-4-2",
    domain: "academic",
    domainName: "Academic Independence",
    level: 4,
    title: "Failure Debrief",
    description: "Something went wrong academically. Debrief: what happened, what you learned, what changes.",
    reflectionPrompt: "What will you do differently?",
    difficulty: 2,
  },
  {
    key: "academic-4-3",
    domain: "academic",
    domainName: "Academic Independence",
    level: 4,
    title: "Professor Relationship",
    description: "Build a relationship with a teacher beyond just class.",
    reflectionPrompt: "What did that involve?",
    difficulty: 2,
  },

  // Level 5: Trailblazer
  {
    key: "academic-5-1",
    domain: "academic",
    domainName: "Academic Independence",
    level: 5,
    title: "No Reminders Academic Week",
    description: "Manage all academic deadlines without external reminders.",
    reflectionPrompt: "What did you miss? What held?",
    difficulty: 3,
  },
  {
    key: "academic-5-2",
    domain: "academic",
    domainName: "Academic Independence",
    level: 5,
    title: "Study Group",
    description: "Form or join a study group. Participate. Evaluate usefulness.",
    reflectionPrompt: "Did it help? Why/why not?",
    difficulty: 3,
  },
  {
    key: "academic-5-3",
    domain: "academic",
    domainName: "Academic Independence",
    level: 5,
    title: "Course Planning",
    description: "Research courses for next semester/year. Create a plan.",
    reflectionPrompt: "How did you decide?",
    difficulty: 3,
  },

  // Level 6: Navigator
  {
    key: "academic-6-1",
    domain: "academic",
    domainName: "Academic Independence",
    level: 6,
    title: "Academic Independence Audit",
    description: "Assess: what academic skills are solid? What still needs support?",
    reflectionPrompt: "Where are the gaps?",
    difficulty: 3,
  },
  {
    key: "academic-6-2",
    domain: "academic",
    domainName: "Academic Independence",
    level: 6,
    title: "College Simulation",
    description: "Treat a week like college: no one checks on you, you manage everything.",
    reflectionPrompt: "What happened?",
    difficulty: 3,
  },

  // Level 7: Expedition Leader
  {
    key: "academic-7-1",
    domain: "academic",
    domainName: "Academic Independence",
    level: 7,
    title: "Academic Survival Guide",
    description: "Write your guide for college academics: study strategies, help resources, deadline management.",
    reflectionPrompt: "What matters most?",
    difficulty: 3,
  },
];
